sudo: false
language: java
jdk:
- oraclejdk9
addons:
  apt:
    packages:
    - oracle-java9-installer
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
install:
- mvn install -U -Dmaven.test.skip=true
script:
- mvn test
after_script:
- npm install -g gitbook-cli
- bash ./scripts/gh-deploy.sh
notifications:
  email: false
env:
  global:
  - ENCRYPTION_LABEL: 9aaa931d81ed
  - COMMIT_AUTHOR_EMAIL: kvndrsslr@gmail.com
  - CODACY_PROJECT_TOKEN: 1e1d7a7ed0a141b798995ace875f83eb
after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/site/jacoco-ut/jacoco.xml